# Generated by Django 3.2.1 on 2022-02-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_customer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_disputes',
            name='email',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customer_disputes',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customer_tickets',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customer_disputes',
            name='Order_Number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customer_disputes',
            name='Subject',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customer_disputes',
            name='Your_Message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
