# Generated by Django 3.2.1 on 2022-02-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_auto_20220218_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_Profile',
        ),
    ]
