# Generated by Django 3.2.1 on 2022-02-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='Feature_tags',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_product',
            name='Meta_Description',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_product',
            name='Meta_tags',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_product',
            name='Product_Colors',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_product',
            name='Product_Estimated_Shipping_Time',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_product',
            name='Size_Price',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_product',
            name='Size_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_product',
            name='Size_qty',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_product',
            name='color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_product',
            name='discount_percentage',
            field=models.IntegerField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_product',
            name='product_qty',
            field=models.IntegerField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_product',
            name='youtube_video_url',
            field=models.URLField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='add_product',
            name='Name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='Slug',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='Tags',
            field=models.CharField(default='', max_length=100),
        ),
    ]
