# Generated by Django 3.2.1 on 2022-02-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220204_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='Feature_tags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
