# Generated by Django 3.2.1 on 2022-02-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220204_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='Size_qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='discount_percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='product_qty',
            field=models.IntegerField(),
        ),
    ]
