# Generated by Django 3.2.1 on 2022-02-04 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220204_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='child_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.child_category'),
        ),
    ]
