# Generated by Django 3.2.1 on 2022-02-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_add_product_child_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='Feature_tags',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='add_product',
            name='Product_Sku',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='Product_Stock',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='Size_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
