# Generated by Django 3.2.1 on 2022-02-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20220204_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_product',
            name='Feature_tags',
        ),
        migrations.RemoveField(
            model_name='add_product',
            name='Meta_Description',
        ),
        migrations.RemoveField(
            model_name='add_product',
            name='Meta_tags',
        ),
        migrations.RemoveField(
            model_name='add_product',
            name='Product_Colors',
        ),
        migrations.RemoveField(
            model_name='add_product',
            name='Product_Estimated_Shipping_Time',
        ),
        migrations.RemoveField(
            model_name='add_product',
            name='Size_Price',
        ),
        migrations.RemoveField(
            model_name='add_product',
            name='Size_name',
        ),
        migrations.RemoveField(
            model_name='add_product',
            name='Size_qty',
        ),
        migrations.RemoveField(
            model_name='add_product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='add_product',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='add_product',
            name='product_qty',
        ),
    ]
