# Generated by Django 3.2.1 on 2022-02-05 16:03

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220204_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature_tags',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='product_colors',
            name='Product_Colors',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
