# Generated by Django 3.2.1 on 2022-02-08 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20220205_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_product',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='main_category',
            options={'ordering': ('-created_at',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='sub_category',
            options={'ordering': ('-created_at',), 'verbose_name': 'sub-category', 'verbose_name_plural': 'sub-categories'},
        ),
        migrations.AlterField(
            model_name='add_product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='product.main_category'),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='product.sub_category'),
        ),
        migrations.AlterField(
            model_name='main_category',
            name='Name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='Name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscatégories', to='product.main_category'),
        ),
    ]
