# Generated by Django 3.2.1 on 2022-02-08 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20220208_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='main_category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sub_category',
            options={},
        ),
        migrations.RemoveField(
            model_name='add_product',
            name='category',
        ),
        migrations.AddField(
            model_name='add_product',
            name='category',
            field=models.ManyToManyField(related_name='ITEM', to='product.Main_category'),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sub_category'),
        ),
        migrations.AlterField(
            model_name='main_category',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='main_category',
            name='Slug',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.main_category'),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
