# Generated by Django 3.2.1 on 2022-02-08 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20220208_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_product',
            name='category',
        ),
        migrations.AddField(
            model_name='add_product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.main_category'),
            preserve_default=False,
        ),
    ]
