# Generated by Django 3.2.1 on 2022-02-08 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20220208_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_image/'),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='youtube_video_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='product.main_category'),
        ),
    ]
