# Generated by Django 3.2.1 on 2022-02-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20220208_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='Product_Buy_Return_Policy',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='Product_Current_Price',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='Product_Description',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='Product_Previous_Price',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='Product_Stock',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
