# Generated by Django 3.2.1 on 2022-02-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_sub_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='Name',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='Product_Sku',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='Slug',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='child_category',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='child_category',
            name='Slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='child_category',
            name='Status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Disabled', 'Disabled')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='main_category',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='main_category',
            name='Slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='main_category',
            name='Status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Disabled', 'Disabled')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='main_category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='main_category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='Status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Disabled', 'Disabled')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
