# Generated by Django 3.2.1 on 2022-02-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0002_auto_20220205_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Current_Banner', models.ImageField(default='', upload_to='Media/Banner')),
            ],
        ),
        migrations.CreateModel(
            name='SettingsServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Current_Featured_Image', models.ImageField(default='', upload_to='Media/services')),
                ('Description', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SettingsSocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=500)),
                ('google_plus', models.CharField(max_length=500)),
                ('twitter', models.CharField(max_length=500)),
                ('linkedin', models.CharField(max_length=500)),
            ],
        ),
    ]
