# Generated by Django 3.2.1 on 2022-02-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0004_settingssociallinks_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingssociallinks',
            name='is_active',
        ),
        migrations.AddField(
            model_name='settingssociallinks',
            name='is_active_fb',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='settingssociallinks',
            name='is_active_google_plus',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='settingssociallinks',
            name='is_active_linkedin',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='settingssociallinks',
            name='is_active_twitter',
            field=models.BooleanField(default='False'),
        ),
    ]
