# Generated by Django 3.2.1 on 2022-02-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0005_auto_20220207_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor_Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Subtitle', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Vendor_Packaging',
            },
        ),
        migrations.CreateModel(
            name='Vendor_ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Duration', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Vendor_Shipping_Method',
            },
        ),
        migrations.CreateModel(
            name='VendorWithdrawals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Withdraw_Method', models.CharField(choices=[('Paypal', 'Paypal'), ('Skrill', 'Skrill'), ('Payoneer', 'Payoneer'), ('Bank', 'Bank')], max_length=100)),
                ('Withdraw_Amount', models.CharField(max_length=100)),
                ('Additional_Reference', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Vendor_Withdrawals',
            },
        ),
    ]
