# Generated by Django 3.2.1 on 2022-02-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0006_vendor_packaging_vendor_shippingmethod_vendorwithdrawals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsbanner',
            name='Current_Banner',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Media/Banner'),
        ),
        migrations.AlterField(
            model_name='settingsservices',
            name='Current_Featured_Image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Media/services'),
        ),
        migrations.AlterField(
            model_name='settingsservices',
            name='Description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='settingsservices',
            name='Title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='settingssociallinks',
            name='facebook',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='settingssociallinks',
            name='google_plus',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='settingssociallinks',
            name='linkedin',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='settingssociallinks',
            name='twitter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_packaging',
            name='Price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_packaging',
            name='Subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_packaging',
            name='Title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_shippingmethod',
            name='Duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_shippingmethod',
            name='Price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_shippingmethod',
            name='Title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorwithdrawals',
            name='Additional_Reference',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorwithdrawals',
            name='Withdraw_Amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorwithdrawals',
            name='Withdraw_Method',
            field=models.CharField(blank=True, choices=[('Paypal', 'Paypal'), ('Skrill', 'Skrill'), ('Payoneer', 'Payoneer'), ('Bank', 'Bank')], max_length=100, null=True),
        ),
    ]
