# Generated by Django 3.2.1 on 2022-02-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0007_auto_20220209_1624'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vendor_packaging',
            table=None,
        ),
        migrations.AlterModelTable(
            name='vendor_shippingmethod',
            table=None,
        ),
        migrations.AlterModelTable(
            name='vendorwithdrawals',
            table=None,
        ),
    ]
