# Generated by Django 3.2.1 on 2022-02-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0010_vendor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
