# Generated by Django 3.2.1 on 2022-02-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0011_auto_20220214_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='phone',
        ),
    ]
