# Generated by Django 3.2.1 on 2022-02-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0012_auto_20220214_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='Website_address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
