# Generated by Django 3.2.1 on 2022-02-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0013_alter_vendor_website_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='Company_Incorporation',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='Direct_Number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='FSSAI_License',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='GST_Number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='Recall_Plan',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='Store_Phone',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='Website_address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='city_town',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='country',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='postcode_zip',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='state',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='store_name',
        ),
    ]
