# Generated by Django 3.2.1 on 2022-02-14 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220213_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_Customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_Vendor',
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Customer', 'CUSTOMER'), ('Vendor', 'VENDOR')], default='Customer', max_length=50, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='CustomerMore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
