# Generated by Django 3.2.1 on 2022-02-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220214_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor_subs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Currency_Symbol', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('Cost', models.CharField(blank=True, max_length=100, null=True)),
                ('Days', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Limitations', models.CharField(blank=True, choices=[('Unlimited', 'Unlimited'), ('Limited', 'Limited')], max_length=250, null=True)),
                ('Details', models.TextField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Vendor_subs',
            },
        ),
    ]
