# Generated by Django 3.2.1 on 2022-02-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_vendor_subs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(blank=True, max_length=100, null=True)),
                ('Amount', models.IntegerField(blank=True, null=True)),
                ('Used', models.IntegerField(blank=True, null=True)),
                ('Type', models.CharField(blank=True, choices=[('Discount by Percentage', 'Discount by Percentage'), ('Discount by Amount', 'Discount by Amount')], max_length=100, null=True)),
                ('Quantity', models.CharField(blank=True, choices=[('Unlimited', 'Unlimited'), ('Limited', 'Limited')], max_length=100, null=True)),
                ('Status', models.CharField(blank=True, choices=[('Activated', 'Activated'), ('Deactivated', 'Deactivated')], max_length=100, null=True)),
                ('Start_Date', models.DateField(blank=True, null=True)),
                ('End_Date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Coupon',
            },
        ),
        migrations.AlterField(
            model_name='vendor_subs',
            name='Currency_Symbol',
            field=models.CharField(blank=True, default='₹', max_length=10, null=True),
        ),
    ]
