# Generated by Django 3.2.1 on 2022-02-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220216_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_coupon',
            name='Status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
