# Generated by Django 3.2.1 on 2022-02-19 12:49

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_admin_disputes_admin_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/slider')),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('text_position', models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right'), ('Center', 'Center')], max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider_Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('font_size', models.IntegerField(blank=True, null=True)),
                ('font_color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None)),
                ('animation', models.CharField(blank=True, choices=[('fadeIn', 'fadeIn'), ('fadeInDown', 'fadeInDown'), ('fadeInLeft', 'fadeInLeft'), ('fadeInRight', 'fadeInRight'), ('fadeInUp', 'fadeInUp'), ('flip', 'flip'), ('flipInX', 'flipInX'), ('flipInY', 'flipInY'), ('SlideInUp', 'SlideInUp'), ('SlideInLeft', 'SlideInLeft'), ('SlideInRight', 'SlideInRight'), ('SlideInDown', 'SlideInDown'), ('RollIn', 'RollIn')], max_length=1000, null=True)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.admin_sliders')),
            ],
        ),
    ]
