# Generated by Django 3.2.1 on 2022-02-19 13:09

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_admin_sliders_slider_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_sliders',
            name='desc_animation',
            field=models.CharField(blank=True, choices=[('fadeIn', 'fadeIn'), ('fadeInDown', 'fadeInDown'), ('fadeInLeft', 'fadeInLeft'), ('fadeInRight', 'fadeInRight'), ('fadeInUp', 'fadeInUp'), ('flip', 'flip'), ('flipInX', 'flipInX'), ('flipInY', 'flipInY'), ('SlideInUp', 'SlideInUp'), ('SlideInLeft', 'SlideInLeft'), ('SlideInRight', 'SlideInRight'), ('SlideInDown', 'SlideInDown'), ('RollIn', 'RollIn')], max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='admin_sliders',
            name='desc_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='admin_sliders',
            name='desc_font_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin_sliders',
            name='desc_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='admin_sliders',
            name='subtitle_animation',
            field=models.CharField(blank=True, choices=[('fadeIn', 'fadeIn'), ('fadeInDown', 'fadeInDown'), ('fadeInLeft', 'fadeInLeft'), ('fadeInRight', 'fadeInRight'), ('fadeInUp', 'fadeInUp'), ('flip', 'flip'), ('flipInX', 'flipInX'), ('flipInY', 'flipInY'), ('SlideInUp', 'SlideInUp'), ('SlideInLeft', 'SlideInLeft'), ('SlideInRight', 'SlideInRight'), ('SlideInDown', 'SlideInDown'), ('RollIn', 'RollIn')], max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='admin_sliders',
            name='subtitle_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='admin_sliders',
            name='subtitle_font_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin_sliders',
            name='subtitle_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='admin_sliders',
            name='title_animation',
            field=models.CharField(blank=True, choices=[('fadeIn', 'fadeIn'), ('fadeInDown', 'fadeInDown'), ('fadeInLeft', 'fadeInLeft'), ('fadeInRight', 'fadeInRight'), ('fadeInUp', 'fadeInUp'), ('flip', 'flip'), ('flipInX', 'flipInX'), ('flipInY', 'flipInY'), ('SlideInUp', 'SlideInUp'), ('SlideInLeft', 'SlideInLeft'), ('SlideInRight', 'SlideInRight'), ('SlideInDown', 'SlideInDown'), ('RollIn', 'RollIn')], max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='admin_sliders',
            name='title_font_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='admin_sliders',
            name='title_font_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin_sliders',
            name='title_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
