# Generated by Django 3.2.1 on 2022-02-09 15:22

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0016_auto_20220208_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Add_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Sku', models.CharField(default='', max_length=1000)),
                ('Name', models.CharField(db_index=True, max_length=300)),
                ('Slug', models.CharField(db_index=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Product_Estimated_Shipping_Time', models.CharField(blank=True, max_length=200, null=True)),
                ('Product_Stock', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('Product_Description', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('Product_Buy_Return_Policy', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('meta_tags', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='featured_image/')),
                ('youtube_video_url', models.CharField(blank=True, max_length=300, null=True)),
                ('Product_Current_Price', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Product_Previous_Price', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Tags', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.main_category')),
                ('child_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.child_category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sub_category')),
            ],
            options={
                'db_table': 'Add_Product',
            },
        ),
        migrations.CreateModel(
            name='Product_Whole_sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.IntegerField(blank=True, null=True)),
                ('discount_perc', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.admin_add_product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Size_qty', models.IntegerField(blank=True, null=True)),
                ('Size_Price', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.admin_add_product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Gallery/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.admin_add_product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Colors', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.admin_add_product')),
            ],
        ),
        migrations.CreateModel(
            name='Feature_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feature_tags', models.CharField(blank=True, max_length=500, null=True)),
                ('color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.admin_add_product')),
            ],
        ),
    ]
