# Generated by Django 3.2.1 on 2022-02-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Admin_Packaging',
            },
        ),
        migrations.CreateModel(
            name='Admin_ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Duration', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Admin_Shipping_Method',
            },
        ),
        migrations.CreateModel(
            name='AdminServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Current_Featured_Image', models.ImageField(blank=True, default='', null=True, upload_to='Media/services')),
                ('Description', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminSocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active_fb', models.BooleanField(default='False')),
                ('google_plus', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active_google_plus', models.BooleanField(default='False')),
                ('twitter', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active_twitter', models.BooleanField(default='False')),
                ('linkedin', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active_linkedin', models.BooleanField(default='False')),
            ],
        ),
        migrations.CreateModel(
            name='AdminWithdrawals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Withdraw_Method', models.CharField(blank=True, choices=[('Paypal', 'Paypal'), ('Skrill', 'Skrill'), ('Payoneer', 'Payoneer'), ('Bank', 'Bank')], max_length=100, null=True)),
                ('Withdraw_Amount', models.CharField(blank=True, max_length=100, null=True)),
                ('Additional_Reference', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Admin_Withdrawals',
            },
        ),
    ]
