# Generated by Django 3.2.1 on 2022-02-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_admin_packaging_admin_shippingmethod_adminservices_adminsociallinks_adminwithdrawals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('Activated', 'Activated'), ('Deactivated', 'Deactivated')], max_length=100)),
                ('Website_Loader', models.ImageField(default='', upload_to='media/Loader/')),
                ('Admin_Loader', models.ImageField(default='', upload_to='media/Loader/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Loaders',
            },
        ),
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_product', models.CharField(blank=True, max_length=1000, null=True)),
                ('total_cost', models.CharField(blank=True, max_length=1000, null=True)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=1000, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Unactive', 'Unactive')], max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Admin_Order_Details',
            },
        ),
    ]
