# Generated by Django 3.2.1 on 2022-02-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_auto_20220222_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaders',
            name='Admin_Loader',
            field=models.ImageField(blank=True, null=True, upload_to='media/Loader/'),
        ),
        migrations.AlterField(
            model_name='loaders',
            name='Website_Loader',
            field=models.ImageField(blank=True, null=True, upload_to='media/Loader/'),
        ),
    ]
