# Generated by Django 3.2.1 on 2022-02-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_auto_20220222_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaders',
            name='Status',
        ),
        migrations.AddField(
            model_name='loaders',
            name='Status_admin_loader',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loaders',
            name='Status_website_loader',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
