# Generated by Django 3.2.1 on 2022-02-22 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_sub_category_category'),
        ('adminapp', '0010_auto_20220222_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_add_product',
            name='Name',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='admin_add_product',
            name='Product_Sku',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='admin_add_product',
            name='Slug',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='admin_add_product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.main_category'),
        ),
        migrations.AlterField(
            model_name='admin_add_product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.sub_category'),
        ),
    ]
