# Generated by Django 3.2.1 on 2022-02-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_auto_20220222_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Declined', 'Declined')], max_length=1000, null=True),
        ),
    ]
