# Generated by Django 3.2.1 on 2022-02-23 05:58

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_order_details_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default='True', null=True)),
                ('Affilate_Bonus', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/affiliate')),
            ],
            options={
                'db_table': 'Affiliate_Info',
            },
        ),
        migrations.CreateModel(
            name='Website_Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Website_Title', models.CharField(blank=True, max_length=1000, null=True)),
                ('wholesale_max_qty', models.IntegerField(blank=True, null=True)),
                ('theme_color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None)),
                ('footer_color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None)),
                ('copyright_color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None)),
            ],
            options={
                'db_table': 'Website_Contents',
            },
        ),
        migrations.CreateModel(
            name='Website_maintainence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('maintainence_text', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Website_Maintainence',
            },
        ),
    ]
